### ISSUE TITLE
TemplateDoesNotExist Error

### ISSUE THREAD

**Issue by marty331** [thclark/wagtail_events#16]
I followed the simple directions for implementing wagtail_events and see it in the admin menu but when I click on the link I get the following error?  Is there something I'm missing?  

<img width="1121" alt="Screen Shot 2020-05-28 at 2 22 32 PM" src="https://user-images.githubusercontent.com/663316/83184204-b6ef0600-a0ee-11ea-9e5f-9096958fc90c.png">

**Comment by marty331** [comment]
I just found the solution!
I needed to also add
`'wagtail.contrib.modeladmin'`
to INSTALLED_APPS.

**Comment by thclark** [comment]
Thanks Marty, I'll add this to the installation instructions for the next release!
