### ISSUE TITLE
App needs `app_label`

### ISSUE THREAD

**Issue by cloudratha** [thclark/wagtail_events#9]
I noticed while trying to index my app with elasticache that your app does not have an app_label defined. 

This throws an error when reaching the AbstractEvent.

Creating an `apps.py` should fix it:
```python
from django.apps import AppConfig


class WagtailEventsConfig(AppConfig):
    name = 'wagtailevents'
    verbose_name = 'WagtailEvents'
```

**Comment by thclark** [comment]
Fixed and released to pypi as v0.3.0.

Thanks for the issue @cloudratha - and congrats on being the first ever issue creator (other than me) on any of my OSS projects. The system works!

**Comment by cloudratha** [comment]
Haha, now you just need someone to do a PR :)
EDIT: Just saw it's named "wagtail_references", is that from another project?

**Comment by thclark** [comment]
FFS hang on

**Comment by thclark** [comment]
*now* it's fixed. Sorry @cloudratha ... dashing between different tasks clearly not paying off today!
[version 0.4.0)
